### ISSUE TITLE
CLI for running the benchmarks

### ISSUE THREAD

**Issue by Kirqkas** [LimeChain/gosemble#324]
1. Configure/store the settings
   - Hardware (cpu, memory, disk, os, arch)
   - Benchmark settings (iterations, etc.)
   - Host (storage, db, cache, etc.)
   - Runtime config (version, modules, etc.)
   - Build flags (opt levels, gc, memory pages, etc.)
2. Compile the runtime to WASM
3. Execute the benchmark tests

**Comment by tgntr** [comment]
turns out it may be possible to use substrate's benchmarking cli since benchmarks are designed to appear as a wasm export. depending on our priorities i think we should consider that for now, because we have many missing parts that would require us to spend time on host side and this would provide a prod-grade solution out of the box, so we could keep our focus on the runtime
